### ISSUE TITLE
Use of Microsoft account as global Administrator

### ISSUE THREAD

**Issue by mkarlsson** [AzureADSamples/WebApp-GroupClaims-DotNet#19]
How does this limitation work? I have my work email account as a Microsoft account to be able to use visual studio online. Is that account unusable then? Or do you only consider some accounts with domain names such as live.com, outlook.com and Hotmail.com and everything else works?

**Comment by dstrockis** [comment]
This should no longer be a limitation - I've tested the sample with MSAs and updated the README accordingly.  We had an issue that caused group and role claims to be absent from the token for guest accounts, which is now fixed.
